"""Tests for the attribution gate.

Two halves, and the second is the one that keeps the gate usable. A check that
fires on correct work teaches everyone to ignore its output, and this product
legitimately writes about models all day: a provider catalog, a run's model id,
a comment explaining what a model returned. None of that is a credit.
"""

import pathlib
import subprocess
import sys

SCRIPT = pathlib.Path(__file__).resolve().parents[1] / "check_no_ai_attribution.py"


def run(*args, cwd=None):
    return subprocess.run(
        [sys.executable, str(SCRIPT), *args],
        capture_output=True, text=True, cwd=cwd,
    )


def check_text(tmp_path, text, name="sample.md"):
    target = tmp_path / name
    target.write_text(text)
    return run(str(target), cwd=tmp_path)


class TestItCatchesACredit:
    def test_a_co_authored_by_trailer(self, tmp_path):
        result = check_text(tmp_path, "A fix\n\nCo-Authored-By: Claude Opus 5 <noreply@anthropic.com>\n")
        assert result.returncode == 1
        assert "Co-Authored-By trailer" in result.stdout

    def test_the_vendor_alone_is_enough(self, tmp_path):
        result = check_text(tmp_path, "Co-Authored-By: Some Bot <bot@openai.com>\n\nCo-Authored-By: x <y@z>\nCo-authored-by: OpenAI Codex <c@d>\n")
        assert result.returncode == 1

    def test_generated_with(self, tmp_path):
        for line in ("Generated with Claude Code", "written by an AI",
                     "Created with ChatGPT", "authored by Copilot"):
            result = check_text(tmp_path, f"note\n\n{line}\n")
            assert result.returncode == 1, line

    def test_a_tool_wrote_this(self, tmp_path):
        result = check_text(tmp_path, "Claude Code wrote the parser.\n")
        assert result.returncode == 1

    def test_a_model_commit_identity(self, tmp_path):
        result = check_text(tmp_path, "contact: noreply@anthropic.com\n")
        assert result.returncode == 1


class TestItLeavesCorrectWorkAlone:
    """Every string here is real text this project ships or could ship."""

    def test_writing_about_a_model_is_not_a_credit(self, tmp_path):
        text = (
            "The catalog lists gemini-3.5-flash-lite and gpt-5.6-sol.\n"
            "The model returned a 429 and the loop backed off.\n"
            "A provider is OpenAI, Google Gemini or Anthropic.\n"
            "Claude Code and Codex both satisfy the e2e method.\n"
            "The driving CLI was Claude Code 2.1.234.\n"
            "Set the default with: vadgr model default openai/gpt-5.6-sol\n"
        )
        result = check_text(tmp_path, text)
        assert result.returncode == 0, result.stdout

    def test_an_ordinary_trailer_is_fine(self, tmp_path):
        result = check_text(tmp_path, "A fix\n\nCo-Authored-By: A Person <person@example.com>\n")
        assert result.returncode == 0, result.stdout

    def test_a_line_that_forbids_the_form_is_not_an_instance_of_it(self, tmp_path):
        """Every document stating this rule has to quote what it forbids."""
        for line in (
            'Never add "Co-Authored-By: Claude" or "Generated with Claude Code".',
            "Do not write generated with Claude in a commit.",
            "The gate rejects a trailer that credits a model, and strips generated by an AI.",
        ):
            result = check_text(tmp_path, line + "\n")
            assert result.returncode == 0, f"fired on the rule's own wording: {line}"

    def test_the_carve_out_does_not_swallow_a_real_credit(self, tmp_path):
        """A credit near unrelated prose still fails."""
        text = "Fix the parser.\n\nGenerated with Claude Code\n"
        assert check_text(tmp_path, text).returncode == 1

    def test_the_gate_and_its_test_are_allowed_to_name_the_forms(self):
        """Otherwise the gate fails on itself, which is how a check gets deleted."""
        repo = SCRIPT.resolve().parents[2]
        result = run("scripts/check_no_ai_attribution.py",
                     "scripts/tests/test_check_no_ai_attribution.py", cwd=repo)
        assert result.returncode == 0, result.stdout


class TestTheRangeMode:
    def test_a_missing_range_refuses_rather_than_passing(self, tmp_path):
        subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
        result = run("--git-range", "deadbeef..HEAD", cwd=tmp_path)
        assert result.returncode == 2
        assert "could not run" in result.stdout

    def test_a_clean_history_passes(self, tmp_path):
        subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
        subprocess.run(["git", "config", "user.email", "a@b.c"], cwd=tmp_path, check=True)
        subprocess.run(["git", "config", "user.name", "A"], cwd=tmp_path, check=True)
        (tmp_path / "f").write_text("x")
        subprocess.run(["git", "add", "f"], cwd=tmp_path, check=True)
        subprocess.run(["git", "commit", "-qm", "a plain message"], cwd=tmp_path, check=True)
        first = subprocess.run(["git", "rev-list", "--max-parents=0", "HEAD"],
                               cwd=tmp_path, capture_output=True, text=True).stdout.strip()
        result = run("--git-range", f"{first}..HEAD", cwd=tmp_path)
        assert result.returncode == 0, result.stdout

    def test_a_credited_commit_in_the_range_fails(self, tmp_path):
        subprocess.run(["git", "init", "-q"], cwd=tmp_path, check=True)
        subprocess.run(["git", "config", "user.email", "a@b.c"], cwd=tmp_path, check=True)
        subprocess.run(["git", "config", "user.name", "A"], cwd=tmp_path, check=True)
        (tmp_path / "f").write_text("x")
        subprocess.run(["git", "add", "f"], cwd=tmp_path, check=True)
        subprocess.run(["git", "commit", "-qm", "base"], cwd=tmp_path, check=True)
        (tmp_path / "f").write_text("y")
        subprocess.run(["git", "commit", "-aqm", "a fix\n\nCo-Authored-By: Claude <noreply@anthropic.com>"],
                       cwd=tmp_path, check=True)
        result = run("--git-range", "HEAD~1..HEAD", cwd=tmp_path)
        assert result.returncode == 1
        assert "Co-Authored-By" in result.stdout
